parameters:
    xola_elasticsearch_proxy:
        client:
            protocol: http
            host: localhost
            port: 9200
            indexes: []

        authenticator: Xola\ElasticsearchProxyBundle\Authenticator
        roles_skip_auth_filter: []
