xola_elasticsearch_proxy:
   path: /elasticsearch/{index}/{slug}
   defaults:
      {
         _controller: 'Xola\\ElasticsearchProxyBundle\\Controller\\ElasticsearchProxyController::proxyAction',
      }
   requirements:
      slug: ".+"
